services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - mongo
      - otel-collector
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=dev
      - PORT=8080
      - OTEL_SERVICE_NAME=grpc-buf
      - MONGO_URL=mongodb://admin:admin@mongo:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongo:
    container_name: mongo
    image: mongo:6.0.3
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.120.0
    depends_on:
      - jaeger
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - 4317:4317

  jaeger:
    image: jaegertracing/all-in-one:1.66.0
    container_name: jaeger
    ports:
      - "16686:16686"  # Web UI
    environment:
      - COLLECTOR_OTLP_ENABLED=true