services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - postgres
      - otel-collector
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=dev
      - PORT=8080
      - OTEL_SERVICE_NAME=grpc-buf
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/grpcbuf?sslmode=disable
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    container_name: postgres
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grpcbuf
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:9.1
    environment:
      PGADMIN_DEFAULT_EMAIL: grpcbuf@buf.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    profiles:
      - debug  

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.120.0
    depends_on:
      - jaeger
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - 4317:4317

  jaeger:
    image: jaegertracing/all-in-one:1.66.0
    container_name: jaeger
    ports:
      - "16686:16686"  # Web UI
    environment:
      - COLLECTOR_OTLP_ENABLED=true

volumes:
  postgres-data:
  pgadmin-data: