environment: prod
server:
  port: 8080
  cors_allowed_origins: []
  run_migrations: true
  log_level: info
  login_rps: 5
  login_burst: 10
database:
  url: ${DATABASE_URL}
  max_conns: 100
  min_conns: 5
  connect_timeout: 60s
security:
  jwt_secret: ${JWT_SECRET}
  jwt_issuer: grpc-buf
  jwt_audience: grpc-buf
  auth_skip_suffixes: ["/RegisterUser", "/LoginUser"]
