name: buf
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}
      - name: Get changed files in the proto folder
        id: changed-proto
        uses: tj-actions/changed-files@v35
        with:
          files: proto/**
      - uses: bufbuild/buf-lint-action@v1
        if: steps.changed-proto.outputs.any_changed == 'true'
        with:
          input: proto
      - uses: bufbuild/buf-breaking-action@v1
        if: steps.changed-proto.outputs.any_changed == 'true'
        with:
          against: 'https://github.com/dipjyotimetia/gRPC-buf.git#branch=main,ref=HEAD~1,subdir=proto'
      - name: Push to schema registry
        if: steps.changed-proto.outputs.any_changed == 'true'
        uses: bufbuild/buf-push-action@v1
        with:
          input: "proto"
          buf_token: ${{ secrets.BUFREGISTRY }}