name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v3'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/1042576031837/locations/global/workloadIdentityPools/ghactions/providers/github-identity-pool-provider'
          service_account: 'gha-deploy@dev-aileron-214211.iam.gserviceaccount.com'

      - uses: 'google-github-actions/deploy-cloudrun@v3'
        with:
          image: 'us-docker.pkg.dev/cloudrun/container/hello:latest'
          service: 'hello-cloud-run'
