name: Deploy

on:
  push:
    branches: [ main ]
env:
  SERVICE: grpc-buf
  REGION: australia-southeast2
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          create_credentials_file: true
          workload_identity_provider: '${{ secrets.GCP_WIF_PROVIDER }}'
          service_account: '${{ secrets.GCP_SA_EMAIL }}'

      - name: Deploy to Cloud Run
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v3'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          source: '.'
          env_vars: |
            ENVIRONMENT=prod
          secrets: |
            DATABASE_URL=projects/${{ secrets.GCP_PROJECT_NUMBER }}/secrets/DATABASE_URL/versions/latest
            JWT_SECRET=projects/${{ secrets.GCP_PROJECT_NUMBER }}/secrets/JWT_SECRET/versions/latest
          flags: >-
            --use-http2
            --allow-unauthenticated
            --concurrency=80
            --cpu=1
            --memory=256Mi
            --max-instances=1
            --cpu-throttling
