name: Deploy

on:
  push:
    branches: [ main ]

env:
  SERVICE: grpc-buf
  REGION: australia-southeast2
  AR_REGION: australia-southeast2
  AR_REPO: grpc-buf

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      DOCKER_BUILDKIT: 1
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      PROJECT_NUMBER: ${{ secrets.GCP_PROJECT_NUMBER }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.PROVIDER_FULL }}
          service_account: ${{ secrets.DEPLOYER_SA_EMAIL }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ secrets.PROJECT_ID }}
      
      - name: Configure Artifact Registry Docker auth
        run: gcloud auth configure-docker "${REGION}-docker.pkg.dev" --quiet

      - name: Build and push Docker image
        run: |
          IMAGE="${REGION}-docker.pkg.dev/${PROJECT_ID}/${AR_REPO}/${SERVICE}:${GITHUB_SHA}"
          echo "IMAGE=${IMAGE}" >> "$GITHUB_ENV"
          docker build -t "${IMAGE}" .
          docker push "${IMAGE}"

      - name: Deploy to Cloud Run
        run: |
          IMAGE=${AR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${AR_REPO}/${GITHUB_REPO}:$GITHUB_SHA
          gcloud run deploy ${SERVICE_NAME:-my-service} \
            --image="$IMAGE" \
            --region=${REGION} \
            --service-account=${RUNTIME_SA_EMAIL} \
            --allow-unauthenticated \
            --set-secrets="DATABASE_URL=projects/${PROJECT_NUMBER}/secrets/${DATABASE_URL}:latest,JWT_SECRET=projects/${PROJECT_NUMBER}/secrets/JWT_SECRET:latest" \
            --set-env-vars "ENVIRONMENT=production"