name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  integration:
    if: github.event_name == 'workflow_dispatch' || vars.RUN_INTEGRATION_TESTS == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          cache: true

      - name: Build and start services
        run: |
          docker compose version
          docker compose up -d --build

      - name: Wait for API readiness
        run: |
          for i in {1..60}; do
            if curl -fsS http://localhost:8080/livez >/dev/null; then echo "API ready"; exit 0; fi
            sleep 2
          done
          echo "API did not become ready in time" >&2
          docker compose logs api || true
          exit 1

      - name: Run integration tests
        env:
          CGO_ENABLED: 0
        run: |
          go test -tags=integration ./tests/integration/... ./cmd/server -v

      - name: Dump container logs on failure
        if: failure()
        run: |
          docker compose ps
          docker compose logs api postgres || true

      - name: Tear down
        if: always()
        run: docker compose down -v

